name: scdl-foveated
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pytorch
  - torchvision
  - opencv
  - imageio
  - pillow
  # OpenEXR Python bindings for saving float EXR masks
  - openexr-python
  - imath
