name: scdl-foveated
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.*
  - torchvision=0.19.*
  - pytorch-cuda=12.1
  - numpy
  - pillow
  - imageio>=2.28
  - scipy
  - pip
  - pip:
      - opencv-python>=4.9
      # optional, enables EXR export; otherwise the script falls back to imageio
      - openexr==1.3.9
      - torchmetrics>=1.4
      - ftfy
      - omegaconf
      - regex
      - scikit-learn
      - submitit
      - termcolor
