name: scdl-foveated
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.*
  - torchvision=0.19.*
  - pytorch-cuda=12.1
  - numpy
  - pillow
  - imageio>=2.28
  - scipy
  - openexr-python
  - pip
  - pip:
      - opencv-python>=4.9
      - torchmetrics>=1.4
      - ftfy
      - omegaconf
      - regex
      - transformers>=4.41
      - kornia>=0.7
      - scikit-learn
      - submitit
      - termcolor
